openapi: 3.0.3
info:
  title: Future Frame API Reference
  description: The Futre Frame REST API documentation.
  version: "0.1.3"
  # termsOfService: https://futureframe.ai/policies/terms-of-use
  contact:
    name: Future Frame Support
    email: support@futureframe.ai
  license:
    name: MIT
    url: https://github.com/futureframeai/ff-openapi/blob/master/LICENSE
servers:
  - url: https://futureframe.ai/api
tags:
  - name: API Keys
    description: Endpoints for managing and authenticating API keys.
  - name: Pre-trained Models
    description: Endpoints for retrieving pre-trained models available for fine-tuning.
  - name: Fine-tuning
    description: Endpoints for initiating and managing the fine-tuning jobs.
  - name: Evaluation
    description: Endpoints for evaluating the performance of fine-tuned models on specified datasets.
  - name: Inference
    description: Endpoint for making predictions using fine-tuned models.
  - name: Fine-tuned Models
    description: Endpoints for accessing and managing models that have been fine-tuned.
  - name: Usage
    description: Endpoints for monitoring usage statistics and quotas.
  - name: Health
    description: Endpoints for checking the health and status of the API service.
security:
  - ApiKeyAuth: []
paths:
  /api-keys:
    post:
      $ref: "./paths/api_keys/create.yaml"
  /api-keys/{api_key}:
    delete:
      $ref: "./paths/api_keys/delete.yaml"
  /pretrained-models:
    get:
      $ref: "./paths/pretrained_models/list.yaml"
  # /pretrained-models/{id}:
  #   get:
  #     $ref: "./paths/pretrained_models/model_details.yaml"
  /finetuning:
    post:
      $ref: "./paths/finetuning/launch_job.yaml"
    get:
      $ref: "./paths/finetuning/list.yaml"
  /finetuning/{job_id}:
    get:
      $ref: "./paths/finetuning/results.yaml"
  /evaluation:
    post:
      $ref: "./paths/evaluation/run.yaml"
    get:
      $ref: "./paths/evaluation/list.yaml"
  /evaluation/{job_id}:
    get:
      $ref: "./paths/evaluation/results.yaml"
  /inference/{model_name}:
    post:
      $ref: "./paths/inference/run.yaml"
  /models:
    get:
      $ref: "./paths/finetuned_models/list.yaml"
  /models/{model_name}:
    get:
      $ref: "./paths/finetuned_models/model_details.yaml"
    delete:
      $ref: "./paths/finetuned_models/delete_model.yaml"
  /usage:
    get:
      $ref: "./paths/usage/get.yaml"
  /health:
    get:
      $ref: "./paths/health/get.yaml"
components:
  securitySchemes:
    $ref: "./schemas/security.yaml"
