name: Validate OpenAPI definition
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  validate_openapi:
    runs-on: ubuntu-latest
    name: Swagger Editor Validator Service
    steps:
      - uses: actions/checkout@v2
      - name: Validate OpenAPI definition
        uses: char0n/swagger-editor-validate@v1
        with:
          definition-file: openapi.yaml